Issue220 relationship
monarch-initiative/MAxO pull request #221
Opened 2021-02-24 20:48 UTC by LCCarmody

Trying to edit the pharmacotherapy branch. THis is what I used for my logical definition

" "'pharmacotherapy' and ('therapeutic_uses' some 'chemical entity' and ('has_role' some %s))"
  vars: - drug_role"

But when running the reasoner, this puts 'pharmacotherapy' under 'independent continuant', which is not correct.

Not sure how to think about

2021-02-24 20:49 UTC, LCCarmody commented
@matentzn no hurry, but this is the current state of things.

2021-02-24 22:27 UTC, matentzn requested changes

2021-02-24 22:27 UTC, matentzn commented on src/patterns/dosdp-patterns/pharmacotherapy_chemicalsubstance.yaml
> +  text: "'pharmacotherapy' and ('therapeutic_uses' some 'chemical entity' and ('has_role' some %s))"
Should be:

```
text: "'pharmacotherapy' and ('therapeutic_uses' some ('chemical entity' and ('has_role' some %s)))"
```

2021-02-25 15:49 UTC, LCCarmody commented on src/patterns/dosdp-patterns/pharmacotherapy_chemicalsubstance.yaml
> +  text: "'pharmacotherapy' and ('therapeutic_uses' some 'chemical entity' and ('has_role' some %s))"
works

2021-02-25 15:53 UTC, LCCarmody commented
For some reason I cannot accept your change, but I did it manually, so I know it works. Will implement

2021-02-25 16:01 UTC, LCCarmody commented
close #220

2021-02-25 16:01 UTC, merged